#cloud-config
package_update: true
package_upgrade: true
packages:
  - openvpn
  - easy-rsa
  - iptables-persistent
  - ca-certificates
  - curl
  - apt-transport-https
  - lsb-release
  - gnupg
  - expect

write_files:
  - path: /etc/cloud-init-vars.sh
    permissions: "0644"
    content: |
      export USERNAME='appsvc_ovpn'
      export KEYVAULT_NAME='kv-bwc-openvpn-dev-weu'
      export KEYVAULT_SSH_KEY_NAME='ssh-private-key'

runcmd:
  # Enable IP forwarding
  - sed -i 's/^#\s*\(net\.ipv4\.ip_forward=1\)/\1/' /etc/sysctl.conf
  - sysctl -p

  # Install Azure CLI
  - curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg
  - AZ_DIST=$(lsb_release -cs)
  - echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_DIST main" > /etc/apt/sources.list.d/azure-cli.list
  - apt-get update && apt-get install -y azure-cli

  # Login to Azure using Managed Identity
  - |
    if az login --identity --output none; then
      echo "[Console Log]: Azure CLI Login Successful!"
    else
      echo "[Console Log]: Azure CLI Login Failed!" >&2
      exit 1
    fi

  # Create Web App SSH User Account
  - |
    . /etc/cloud-init-vars.sh

    if ! id "$USERNAME" &>/dev/null; then
      useradd -m -s /bin/bash "$USERNAME"
      mkdir -p /home/"$USERNAME"/.ssh
      chown "$USERNAME":"$USERNAME" /home/"$USERNAME"/.ssh
      chmod 700 /home/"$USERNAME"/.ssh
      echo "[Console Log]: $USERNAME Created!"
    fi

    if [ ! -f /home/"$USERNAME"/.ssh/id_rsa ]; then
      ssh-keygen -t rsa -b 4096 -f /home/"$USERNAME"/.ssh/id_rsa -N ""
      chown "$USERNAME":"$USERNAME" /home/"$USERNAME"/.ssh/id_rsa*
      chmod 600 /home/"$USERNAME"/.ssh/id_rsa
      chmod 644 /home/"$USERNAME"/.ssh/id_rsa.pub
      cat /home/"$USERNAME"/.ssh/id_rsa.pub >> /home/"$USERNAME"/.ssh/authorized_keys
      chown "$USERNAME":"$USERNAME" /home/"$USERNAME"/.ssh/authorized_keys
      chmod 600 /home/"$USERNAME"/.ssh/authorized_keys
      
      echo "[Console Log]: SSH Key Generated and Public Key Added to authorized_keys!"
        fi


    # Upload SSH Private Key to Azure Key Vault
  - |
    . /etc/cloud-init-vars.sh
    export sshPrivateKey=$(cat /home/"$USERNAME"/.ssh/id_rsa)
    az keyvault secret set --name "$KEYVAULT_SSH_KEY_NAME" --vault-name "$KEYVAULT_NAME" --value "$sshPrivateKey" --output none
    echo "[Console Log]: SSH Private Key Uploaded to Key Vault!"

  # Prepare Easy-RSA environment
  - |
    echo "Creating EasyRSA environment..."
    make-cadir /etc/openvpn/easy-rsa
    chown -R root:root /etc/openvpn/easy-rsa
    cd /etc/openvpn/easy-rsa/
    ./easyrsa --batch init-pki

  # Build CA using expect
  - |
    . /etc/cloud-init-vars.sh
    export caPassword=$(az keyvault secret show --name certificateAuthPassword --vault-name "$KEYVAULT_NAME" --query value -o tsv)

    expect <<EOF
    log_user 0
    set timeout -1
    set caPassword "$caPassword"
    spawn /etc/openvpn/easy-rsa/easyrsa --batch --req-cn="ca-[exec hostname]" build-ca
    expect "Enter New CA Key Passphrase:"
    send "\$caPassword\r"
    expect "Confirm New CA Key Passphrase:"
    send "\$caPassword\r"
    expect eof
    EOF
    echo "EasyRSA Certificate Authority Created!"

  # Generate DH and server certificates
  - /etc/openvpn/easy-rsa/easyrsa gen-dh
  - /etc/openvpn/easy-rsa/easyrsa --batch gen-req $(hostname) nopass

  # Generate Server Certificate
  - |
    . /etc/cloud-init-vars.sh
    export caPassword=$(az keyvault secret show --name certificateAuthPassword --vault-name "$KEYVAULT_NAME" --query value -o tsv)

    echo "Generating Server Certificate..."
    cd /etc/openvpn/easy-rsa/

    expect <<EOF
    log_user 0
    set timeout -1
    set caPassword "$caPassword"
    spawn ./easyrsa --batch sign-req server "$(hostname)"
    expect {
      "Enter pass phrase for*" {
        send "\$caPassword\r"
        exp_continue
      }
      eof
    }
    EOF

  # Copy generated files to OpenVPN directory
  - cp /etc/openvpn/easy-rsa/pki/dh.pem /etc/openvpn/easy-rsa/pki/ca.crt /etc/openvpn/easy-rsa/pki/issued/$(hostname).crt /etc/openvpn/easy-rsa/pki/private/$(hostname).key /etc/openvpn/

  # Create CCD directory and sample config
  - mkdir -p /etc/openvpn/ccd

  # Write OpenVPN server configuration
  - |
    cat <<EOF > /etc/openvpn/server.conf
    # OpenVPN server configuration file
    # Built for $(hostname), Deployed via IaC
    port 1194
    proto udp
    dev tun
    ca ca.crt
    cert $(hostname).crt
    key $(hostname).key
    dh dh.pem
    topology subnet
    server 10.8.0.0 255.255.255.0
    ifconfig-pool-persist /var/log/openvpn/ipp.txt
    client-config-dir ccd
    persist-key
    persist-tun
    status /var/log/openvpn/openvpn-status.log
    verb 4
    EOF

  # Enable and start OpenVPN service
  - systemctl enable openvpn@server
  - systemctl start openvpn@server

  # Set up NAT and routing
  - iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
  - iptables -I FORWARD -i tun0 -o tun0 -j DROP
  - netfilter-persistent save
